language: node_js
node_js:
  - 16
cache: npm
script:
  - "$(npm bin)/knapsack-pro-jest --runInBand"
env:
  global:
    - KNAPSACK_PRO_CI_NODE_TOTAL=2
    # allows to be able to retry failed tests on one of parallel job (CI node)
    - KNAPSACK_PRO_FIXED_QUEUE_SPLIT=true
    - KNAPSACK_PRO_TEST_FILE_PATTERN="**/__tests__/*.test.ts"

  matrix:
    - KNAPSACK_PRO_CI_NODE_INDEX=0
    - KNAPSACK_PRO_CI_NODE_INDEX=1
